apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: feedback-system
  namespace: aksel-sommerstudenter
  labels:
    team: aksel-sommerstudenter

spec:
  image: {{ image }}
  port: 3000

  #image: ghcr.io/navikt/myapplication:417dcaa2c839b9da72e0189e2cfdd4e90e9cc6fd
  #       ^--- interpolated from the ${{ env.docker_image }} variable in the action
  ingresses:
    - "https://feedbacksystem.dev.intern.nav.no"
  liveness:
    path: /api/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /api/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
