name: Deploy dev to gcp
on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build_and_deploy:
    name: Build and deploy to dev-gcp
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - uses: actions/checkout@v2
      - name: Install deps
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Build application
        run: npm build:next

      - name: Build docker image
        run: docker build -t ${{ env.DOCKER_TAG }} .
      - name: Push docker image
        run: |
          docker push ${{ env.DOCKER_TAG }}
      - name: Create tag and release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
          commitish: ${{ github.sha }}
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/dev/nais.yaml
          CLUSTER: dev-gcp
          IMAGE: ${{ env.DOCKER_TAG }}
