name: Build, push, and deploy

on:
  push:
    branches: ["dev"]

env:
  docker_image: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    name: Install deps
    run: npm install
#    name: Jest tests
#    run: npm run test
    name: Build application
    run: npm run build
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.docker_image }}

  deploy:
    name: Deploy to NAIS
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais.yaml
          VAR: image=${{ env.docker_image }}
